<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" 
    integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" 
    crossorigin="anonymous">
    
    <link rel="stylesheet" href="css/css-login.css">
    <title>Criar Conta</title>
  </head>
  <body>
    <div class="container d-flex justify-content-center">
      <div class="row d-flex justify-content-center">
        <div class="col-md-4  align-self-center shadow-lg rounded" id="div-login">
          <div id="titulo">Criar Conta</div>
            <form action="/cadastro" method="POST">
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                  </span>
                </div>
                <input type="text" class="form-control" placeholder="Nome" aria-label="Nome" name="nome">
              </div>     
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                  </span>
                </div>
                <input type="text" class="form-control" placeholder="E-mail" aria-label="Email" name="email">
              </div>       
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">
                    <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                  </span>
                </div>
                <input type="password" class="form-control" placeholder="Senha" aria-label="Senha" name="senha">
              </div>
              <?php if(isset($_GET['inputvazio'] ) &&  $_GET['inputvazio'] == 'true'){?> 
                <div class="text text-danger">
                Por favor preencha todos os campos!
                </div>
              <?php } ?>
              <?php if(isset($_GET['emailvalido'] ) &&  $_GET['emailvalido'] == 'false'){?> 
                <div class="text text-danger">
                  Já exite uma conta com esse E-mail, por favor insira outro!
                </div>
              <?php } ?>
              <div id="opcao" >
                <p>Ou <a href="/login">já tenho uma conta</a></p>
              </div>
              <button type="submit" class="btn btn-dark " id="btn-entrar">Cadastrar</button>
            </form>
        </div>
      </div>
    </div>

  </body>
</html>