<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h1{
            color: green;
        }
        h3{
            color:red;
        }
       
    </style>
</head>
<body>
    <h1>Dashboard</h1>
    <h3>Seu Nome é: <?php echo $_SESSION['nome']?></h3>
    <h3>Seu ID é: <?php echo $_SESSION['id']?></h3>
    <h3><a href="/sair">Fazer logoff</h3>
</body>
</html>

