<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">

    <!-- fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" 
    integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" 
    crossorigin="anonymous">
    
    <link rel="stylesheet" href="css/css-login.css">
    <title>Fazer Login</title>
  </head>
  <body>
    <div class="container d-flex justify-content-center">
      <div class="row d-flex justify-content-center">
        <div class="col-md-4  align-self-center shadow-lg rounded" id="div-login">
          <div id="titulo">LOGIN</div>
            <form action="/login" method="POST">
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                  </span>
                </div>
                <input type="text" class="form-control" placeholder="Email" aria-label="Email" name="email">
              </div>       
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">
                    <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                  </span>
                </div>
                <input type="password" class="form-control" placeholder="Senha" aria-label="Senha" name="senha">
              </div>
              <?php if(isset($_GET['logado'] ) &&  $_GET['logado'] == 'false'){?> 
                <div class="text text-danger">
                  E-mail e senha inválidos(s)
                </div>
              <?php } ?> 
              <?php if(isset($_GET['inputvazio'] ) &&  $_GET['inputvazio'] == 'true'){?> 
                <div class="text text-danger">
                Por favor preencha todos os campos!
                </div>
              <?php } ?> 
              <div id="opcao" >
                <p>Ou <a href="">esqueci a Senha</a></p>
                <p>Não tem uma conta? <a href="/cadastro">Inscreva-se</a></p>
              </div>         
              <button type="submit" class="btn btn-dark " id="btn-entrar">Entrar</button>
            </form>
        </div>
      </div>
    </div>

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
  </body>
</html>